POST http://localhost:8080/reg
Content-Type: application/x-www-form-urlencoded

login=test&password=123456&name=Test

###
POST http://localhost:8080/aut
Content-Type: application/x-www-form-urlencoded

login=test&password=123456

###

GET http://localhost:8080/calculation?num1=30&num2=15&type=div

###

GET http://localhost:8080/logout

###